### ISSUE TITLE
State parameter not shown

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/aspnet-samples#4]
In the /authorize endpoint when selecting the login with Auth0 option, ´state´ parameter is not on the URL (But it is in the /login right after /authorize).

Also, in the callback, the parameter ´state´ is present in /callback, but not in the Alloweb callback URL "LoginCallback.ashx", just like ´code´ parameter.

![screenshot_2](https://user-images.githubusercontent.com/15818783/38373209-ab158d80-38be-11e8-821f-841392729e4f.png)

**Comment by jerriep** [comment]
Closing as these libraries have been deprecated
