### ISSUE TITLE
upgrade  to .net framework 4.7?

### ISSUE THREAD

**Issue by radupopConnatix** [auth0-samples/aspnet-samples#5]
Any chance to upgrade the webapi to .net framerwork 4.7?

**Comment by jerriep** [comment]
The Web API sample in this repository is not being used anymore. You should use the sample linked to from the [Quickstart](https://auth0.com/docs/quickstart/backend/webapi-owin).

Regards .NET 4.7, we have had complaints in the past when we did that from people wanting to use an older version of the framework. If you want use the latest, you can simply upgrade the project yourself.
